name: Remote

on:
  workflow_call:
  workflow_dispatch:

jobs:
  start-child:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run something"
          echo  ${{ github.repository }}

  do-job:
    runs-on: ubuntu-latest
    needs: [ start-child ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "master"
          repository: dbhao/github_action_test_2
          fetch-depth: 0
          submodules: recursive

  finish-child:
    runs-on: ubuntu-latest
    needs: [ do-job ]
    if: ${{ always() }}
    steps:
      - run: |
          echo "Finished"
